# For legacy Python projects, we can still benefit from some modern tooling
[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded by ^/ will apply only to files and directories
# in the root of the project.
(
  ^/\.venv
  | ^/venv
  | __pycache__
  | \.egg-info
  | \.mypy_cache
  | \.pytest_cache
  | frontend/node_modules
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Gradually enable this
disallow_incomplete_defs = false  # Gradually enable this

# Per-module options
[[tool.mypy.overrides]]
module = "flask_cors"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true

# Exclude certain paths
exclude = [
    "test_.*\\.py$",
    "debug_.*\\.py$",
    "__pycache__",
    ".venv",
    ".mypy_cache"
]
